version: '3'
services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    networks:
      - app_network

  backend:
    build: 
      context: ../backend  # Adjust this path as needed
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: frontend_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - adminer
    networks:
      - app_network

networks:
  app_network:
    driver: bridge