version: '3'
services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: frontend_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge