version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network
    tmpfs:
      - /var/cache/nginx
      - /var/run

networks:
  app_network:
    external: true
