version: '3.8'

services:
  frontend_nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend

  frontend:
    build: .
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production

networks:
  default:
    name: frontend_network
    driver: bridge