version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ubuntu
      POSTGRES_PASSWORD: twende@1357
      POSTGRES_DB: ubuntu
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ubuntu"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    environment:
      - POSTGRES_USER=ubuntu
      - POSTGRES_PASSWORD=twende@1357
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ubuntu
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    
  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  postgres_data:


networks:
  app_network:
    external: true