version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - adminer

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://ubuntu:twende@1357@db/fast_api
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ubuntu
      POSTGRES_PASSWORD: twende@1357
      POSTGRES_DB: fast_api
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    expose:
      - "8080"
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  default:
    name: app_network
    external: true

# version: '3.8'

# services:
#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     depends_on:
#       - backend
#       - adminer

#   backend:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       - DATABASE_URL=postgresql://ubuntu:twende@1357@db/fast_api
#     expose:
#       - "8000"
#     depends_on:
#       - db

#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: your_username
#       POSTGRES_PASSWORD: your_password
#       POSTGRES_DB: your_database
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   adminer:
#     image: adminer
#     expose:
#       - "8080"
#     depends_on:
#       - db

# volumes:
#   postgres_data: